#!/usr/bin/env python3
"""Refresh tickers-etf.js from Naver Finance's ETF master.

Naver returns all listed Korean ETFs (~1,000+) as a single JSON, with each
entry tagged by category (etfTabCode 1-7). Response is EUC-KR encoded for
Korean names so we have to decode explicitly.

Run from GitHub Actions runner (no CORS proxy needed) or locally. Designed
to be idempotent — overwrites tickers-etf.js with the current Naver list.
"""

import json
import os
import sys

import requests

NAVER_ETF_URL = "https://finance.naver.com/api/sise/etfItemList.nhn"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_FILE = os.path.join(ROOT, "tickers-etf.js")

CATEGORY = {
    1: "국내지수",
    2: "국내테마",
    3: "파생/레버리지",
    4: "해외주식",
    5: "원자재",
    6: "채권",
    7: "기타",
}


def main():
    r = requests.get(
        NAVER_ETF_URL,
        headers={
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
            "Referer": "https://finance.naver.com/",
            "Accept": "application/json",
        },
        timeout=30,
    )
    r.raise_for_status()

    # Naver returns EUC-KR for legacy endpoints — decode explicitly
    text = r.content.decode("euc-kr", errors="replace")
    j = json.loads(text)
    items = j.get("result", {}).get("etfItemList") or []
    if not items:
        print("ERROR: empty ETF list", file=sys.stderr)
        sys.exit(1)

    seen = set()
    rows = []
    for it in items:
        code = (it.get("itemcode") or "").strip()
        name = (it.get("itemname") or "").strip()
        cat = CATEGORY.get(int(it.get("etfTabCode") or 0), "기타")
        if not code or len(code) != 6 or code in seen or not name:
            continue
        seen.add(code)
        name_esc = name.replace("\\", "\\\\").replace("'", "\\'")
        rows.append(f"  '{code}': {{ name: '{name_esc}', mkt: 'ETF', sector: '{cat}' }},")
    rows.sort()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("/* =====================================================================\n")
        f.write(f" * Korean ETF Master — {len(rows)} ETFs from Naver Finance\n")
        f.write(" * Source: finance.naver.com/api/sise/etfItemList.nhn (EUC-KR decoded)\n")
        f.write(" * Categories: 국내지수 / 국내테마 / 파생/레버리지 / 해외주식 / 원자재 / 채권 / 기타\n")
        f.write(" * Auto-generated by scripts/fetch_etf_list.py — do not edit by hand\n")
        f.write(" * ===================================================================== */\n")
        f.write("window.TICKER_ETF_REGISTRY = {\n")
        f.write("\n".join(rows))
        f.write("\n};\n")

    print(f"Wrote {len(rows)} ETFs to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
